/*******************************************************************************
 * Copyright (c) 2008 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     IBM Corporation - initial API and implementation
 *******************************************************************************/
 
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_eclipse_equinox_internal_security_osx_OSXProvider */

#ifndef _Included_org_eclipse_equinox_internal_security_osx_OSXProvider
#define _Included_org_eclipse_equinox_internal_security_osx_OSXProvider
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_eclipse_equinox_internal_security_osx_OSXProvider
 * Method:    getPassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_eclipse_equinox_internal_security_osx_OSXProvider_getPassword
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     org_eclipse_equinox_internal_security_osx_OSXProvider
 * Method:    setPassword
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT void JNICALL Java_org_eclipse_equinox_internal_security_osx_OSXProvider_setPassword
  (JNIEnv *, jobject, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
