/*******************************************************************************
 * Copyright (c) 2017 IBM Corporation and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * 
 * Contributors:
 *     LinuxPasswordProviderMessages.java
 *******************************************************************************/
/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class LinuxPasswordProvider */

#ifndef _Included_LinuxPasswordProvider
#define _Included_LinuxPasswordProvider
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     LinuxPasswordProvider
 * Method:    getMasterPassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_eclipse_equinox_internal_security_linux_LinuxPasswordProvider_getMasterPassword
  (JNIEnv *, jobject);

/*
 * Class:     LinuxPasswordProvider
 * Method:    saveMasterPassword
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_eclipse_equinox_internal_security_linux_LinuxPasswordProvider_saveMasterPassword
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
