name: Perform Code Clean
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * *'

jobs:
  clean-code:
    uses: eclipse-platform/eclipse.platform.releng.aggregator/.github/workflows/cleanCode.yml@master
    with:
      author: Eclipse Equinox Bot <equinox-bot@eclipse.org>
      do-quickfix: false
      do-cleanups: true
    secrets:
      token: ${{ secrets.EQUINOX_BOT_PAT }}
